### ISSUE TITLE
rest-client error

### ISSUE THREAD

**Issue by mcdavon** [adamsb6/s3_file#126]
Hi, I'm running into issues with the rest-client error and can't figure out how to resolve it. Here's the error, FATAL: LoadError: cannot load such file -- rest-client

It appears the version is not compatible but I'm sure, please can anyone advise a fix?

**Comment by carlwain74** [comment]
Same here. My story is that I am migrating our Chef 12.x server to latest version. The same cookbook works fine in 12.x

### Extract from stack output

>>>> Caused by LoadError: cannot load such file -- rest-client
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:216:in `client'
/var/chef/cache/cookbooks/s3_file/providers/default.rb:8:in `block in class_from_file'
(eval):2:in `block in action_create'

I initially had v2.8.5, but I see the same issue with 2.7.0 version which was working in Chef 12.x
