### ISSUE TITLE
Convergence fails after upgrading Chef omnibus package

### ISSUE THREAD

**Issue by eherot** [adamsb6/s3_file#60]
The `mime-types` Gem is not automatically re-installed so you get this error:

```
Gem::LoadError
--------------
Could not find 'mime-types' (< 3.0, >= 1.16) among 105 total gem(s)
Checked in 'GEM_PATH=/home/eherot/.gem/ruby/2.1.0:/opt/chef/embedded/lib/ruby/gems/2.1.0', execute `gem env` for more information

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/s3_file/libraries/s3_file.rb:210:in `client'
/var/chef/cache/cookbooks/s3_file/providers/default.rb:8:in `block in class_from_file'
```

The workaround is this to run this:

```
sudo /opt/chef/embedded/bin/gem install rest-client --version '= 1.7.3'
```

...which re-installs `rest-client` and its various dependencies (which is actually just `mime-types`).

**Comment by eherot** [comment]
Thinking about it this is probably more of a bug in `chef_gem` than `s3_file` but I felt you should still know about it.

**Comment by whiteadam** [comment]
Same issue here.

**Comment by joekiller** [comment]
FYI 2.7 is live with this fix.
