### ISSUE TITLE
rest-client fails to build.  chef-client fails when using s3_file LWRP

### ISSUE THREAD

**Issue by rickhull** [adamsb6/s3_file#65]
```
[root@qa-160310170214-indexer-storm-worker-01 ~]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@qa-160310170214-indexer-storm-worker-01 ~]# chef-client --version
Chef: 12.8.1
```

```
[root@qa-160310170214-indexer-storm-worker-01 ~]# chef-client
# ...
  * s3_file[/xxx/xxx] action create
  Recipe: s3_file::dependencies
    * chef_gem[rest-client] action install

      ================================================================================
      Error executing action `install` on resource 'chef_gem[rest-client]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of /opt/chef/embedded/bin/gem install rest-client -q --no-rdoc --no-ri -v "1.8.0" ----
      STDOUT: Building native extensions.  This could take a while...
      STDERR: ERROR:  Error installing rest-client:
        ERROR: Failed to build gem native extension.

          current directory: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/unf_ext-0.0.7.2/ext/unf_ext
      /opt/chef/embedded/bin/ruby -r ./siteconf20160311-5778-1jqsnxx.rb extconf.rb
      checking for main() in -lstdc++... *** extconf.rb failed ***
      Could not create Makefile due to some reason, probably lack of necessary
      libraries and/or headers.  Check the mkmf.log file for more details.  You may
      need configuration options.

      Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/chef/embedded/bin/ruby
        --with-static-libstdc++
        --without-static-libstdc++
        --with-stdc++lib
        --without-stdc++lib
      /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
      You have to install development tools first.
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:552:in `try_link0'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:567:in `try_link'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:747:in `try_func'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:978:in `block in have_library'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:923:in `block in checking_for'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:922:in `checking_for'
        from /opt/chef/embedded/lib/ruby/2.1.0/mkmf.rb:973:in `have_library'
        from extconf.rb:6:in `<main>'

      To see why this extension failed to compile, please check the mkmf.log which can be found here:

        /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/unf_ext-0.0.7.2/mkmf.log

      extconf failed, exit code 1

      Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/unf_ext-0.0.7.2 for inspection.
      Results logged to /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/unf_ext-0.0.7.2/gem_make.out
      ---- End output of /opt/chef/embedded/bin/gem install rest-client -q --no-rdoc --no-ri -v "1.8.0" ----
      Ran /opt/chef/embedded/bin/gem install rest-client -q --no-rdoc --no-ri -v "1.8.0" returned 1

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/s3_file/recipes/dependencies.rb:1:in `from_file'
      /var/chef/cache/cookbooks/s3_file/providers/default.rb:7:in `block in class_from_file'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/s3_file/recipes/dependencies.rb

        1: chef_gem "rest-client" do
        2:   action :install
        3: end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/s3_file/recipes/dependencies.rb:1:in `from_file'

      chef_gem("rest-client") do
        package_name "rest-client"
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :chef_gem
        cookbook_name "s3_file"
        recipe_name "dependencies"
        gem_binary "/opt/chef/embedded/bin/gem"
      end
```

**Comment by rickhull** [comment]
I wonder if s3_file shouldn't be using net/http instead.  Also, I'm not sure why rest-client needs a Makefile either.

**Comment by rickhull** [comment]
It looks like the failure is a lack of `gcc`.  Which makes the claim of `s3_file` being "pure Ruby" false.

```
[root@qa-160310170214-indexer-storm-worker-01 ~]# cat /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/unf_ext-0.0.7.2/mkmf.log
"gcc -o conftest -I/opt/chef/embedded/include/ruby-2.1.0/x86_64-linux -I/opt/chef/embedded/include/ruby-2.1.0/ruby/backward -I/opt/chef/embedded/include/ruby-2.1.0 -I. -I/opt/chef/embedded/include -O2 -O3 -g -pipe -I/opt/chef/embedded/include   -I/opt/chef/embedded/include -O2 -O3 -g -pipe -fPIC conftest.c  -L. -L/opt/chef/embedded/lib -Wl,-R/opt/chef/embedded/lib -L/opt/chef/embedded/lib -Wl,-R/opt/chef/embedded/lib -L. -Wl,-rpath,/opt/chef/embedded/lib -fstack-protector -L/opt/chef/embedded/lib -rdynamic -Wl,-export-dynamic -L/opt/chef/embedded/lib  -Wl,-R/opt/chef/embedded/lib      -Wl,-R -Wl,/opt/chef/embedded/lib -L/opt/chef/embedded/lib -lruby  -lpthread -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

[root@qa-160310170214-indexer-storm-worker-01 ~]# which gcc
/usr/bin/which: no gcc in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
```

**Comment by rickhull** [comment]
Also, since rest-client is not in Ruby's Standard Library, I'm wondering how this statement can possibly be true:

> This LWRP has no dependencies beyond the Ruby standard library, so it can be used on the first run of Chef.

**Comment by rickhull** [comment]
Worked around by installing `gcc` and `gcc-c++` on CentOS

**Comment by joekiller** [comment]
Yeah this was true until chef removed rest-client from its core.

**Comment by rickhull** [comment]
I see.  Should we add something like

```
package "gcc" do
  action :install
end

yum_package "gcc-c++" do
  action :install
end
```

e.g. for RH-family

**Comment by joekiller** [comment]
Please reopen if this still happens.
