### ISSUE TITLE
Credentials specified but not used?

### ISSUE THREAD

**Issue by rickhull** [adamsb6/s3_file#66]
The error says no credentials provided, but I am providing the AWS keys, which are shown.

```
  * s3_file[/xxx/xxx/xxx] action create
  Recipe: s3_file::dependencies
    * chef_gem[rest-client] action install (up to date)
    
    ================================================================================
    Error executing action `create` on resource 's3_file[/xxx/xxx/xxx]'
    ================================================================================
    
    ArgumentError
    -------------
    No credentials provided and no instance profile on this machine.
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/s3_file/providers/default.rb:26:in `rescue in block in class_from_file'
    /var/chef/cache/cookbooks/s3_file/providers/default.rb:23:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/search-indexer/recipes/install.rb
    
     58:     s3_file "/xxx/xxx/xxx" do
     59:       bucket                "storm-chef"
     60:       remote_path           "#{artifact}.tar.gz"
     61:       aws_access_key_id     aws_creds['access_key_id']
     62:       aws_secret_access_key aws_creds['secret_access_key']
     63:     end
     64:   }
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/search-indexer/recipes/install.rb:58:in `block in from_file'
    
    s3_file("/xxx/xxx/xxx") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :s3_file
      cookbook_name "search-indexer"
      recipe_name "install"
      bucket "storm-chef"
      remote_path "project.tar.gz"
    end
```

Why don't `aws_access_key_id` and `aws_secret_access_key` show up in the compiled resource?

`aws_creds` is an EncryptedDataBag item

**Comment by rickhull** [comment]
Hm, looks like a problem with my EncryptedDataBag usage.  Closing this for now.

**Comment by rickhull** [comment]
Yep, 100% operator error with the EncryptedDataBagItem.

**Comment by JustLeo** [comment]
How did you resolve it? Thanks.
